title:             杨小嘎
email:             18812668537@163.com
description:       『欲诚其意者，先致其知』
author:             嘎
#baseurl:           "/startbootstrap-clean-blog-jekyll"
baseurl:           ""
url:               "http://yangxiaoga.github.io"

# Social Profiles
twitter_username:  #yangxiaoga
github_username:   yangxiaoga
facebook_username: #yangxiaoga

# 百度统计
analytics:
    baidu:
        siteid: a66e23d778dbfa813dcc8e5ad7b661ec

# Build settings
markdown:          kramdown
highlighter: rouge
paginate:          10 
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
